remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: Java Modular Validators
description: to be used as a utility library in projects to avoid the overhead of writing custom validation frameworks
show_downloads: true